# Numpy

The note covers the following topics:

* array initialization
* array attributes
* array indexing (single element)
* array slicing (subarray)
* reshape
* computations on numpy array 
* aggregation



In [2]:
import numpy as np

## Inintialize array



In [1]:
import numpy as np 
# create len=10 with 0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
# creat 3x5 with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
# create 3x5 array with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [4]:
# create array filled with linear sequence, start 0, ending at 20, stepping at 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# create an array 3x3 uniformally distributed between 0 and 1
np.random.random((3,3))

array([[0.3262544 , 0.72300932, 0.87796151],
       [0.11140263, 0.49350754, 0.84713479],
       [0.51267361, 0.4849454 , 0.18375199]])

In [3]:
# create an array 3x3 normal distributed with mean 0, std dev 1
np.random.normal(0, 1, (3,3))


array([[ 0.36494555,  0.75787044, -1.27597714],
       [ 0.7758699 ,  2.25461967, -0.12817804],
       [ 0.51040171, -0.16924491, -0.60142025]])

In [4]:
#create 3x3 array of random integers in [0, 10]
np.random.randint(0, 10, (3,3))

array([[3, 7, 0],
       [0, 2, 8],
       [5, 5, 1]])

In [6]:
# create 3x3 identity 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# create uninitialized array, 3 integers
np.empty(3)

array([1., 1., 1.])

## Array attributes


In [2]:
import numpy as np 
x1 = np.random.randint(10, size=6)         # 1-d 
x2 = np.random.randint(10, size=(3,4))     # 2-d
x3 = np.random.randint(10, size=(3,4,5))   # 3-d
x4 = np.random.randint(10, size=(3,4,5,6)) # 4-d

In [3]:
print(f"x3 ndim = {x3.ndim}")
print(f"x3 shape = {x3.shape}")
print(f"x3 size = {x3.size}")
print(f"x3 dtype = {x3.dtype}")

x3 ndim = 3
x3 shape = (3, 4, 5)
x3 size = 60
x3 dtype = int64


## Array indexing

In [11]:
import numpy as np 
x1 = np.random.randint(10, size=6)         # 1-d 
x2 = np.random.randint(10, size=(3,4))     # 2-d
x3 = np.random.randint(10, size=(3,4,5))   # 3-d
x4 = np.random.randint(10, size=(3,4,5,6)) # 4-d

In [8]:
print(x1)

# using negative index to access the last element
print(x1[-1])
print(x1[-2])


[7 5 1 3 8 4]
4
8


In [9]:
# 2-d example
# use [i,j] as index
print(x2)
print(x2[0,0]) 

[[6 7 8 3]
 [8 7 2 4]
 [3 0 9 8]]
6


## Array Slicing

The most important property of np sub-array is: it is a **view**, not a copy. Therefore, if you assign the subarray to a variable, and modify it. The change **will be** reflected in the original numpy array.

If you do want to make a copy, you need to do something like the following:

```
x2_sub_copy = x2[:2, :2].copy()
```



In [22]:
import numpy as np 
x1 = np.random.randint(10, size=10)        # 1-d 
x2 = np.random.randint(10, size=(3,4))     # 2-d
x3 = np.random.randint(10, size=(3,4,5))   # 3-d
x4 = np.random.randint(10, size=(3,4,5,6)) # 4-d

### 1-d array

In [23]:

print(x1)
print(f"first 3 elements: {x1[:3]}")
print(f"ele after index 2: {x1[2:]}")
print(f"middle 2 elements: {x1[2:4]}")
print(f"every other element: {x1[::2]}")
print(f"every other element, starting from index 1: {x1[1::2]}")

[6 9 9 7 2 4 7 1 5 3]
first 3 elements: [6 9 9]
ele after index 2: [9 7 2 4 7 1 5 3]
middle 2 elements: [9 7]
every other element: [6 9 2 7 5]
every other element, starting from index 1: [9 7 4 1 3]


### 2-d or more


In [28]:

x2


array([[3, 0, 8, 8],
       [1, 4, 0, 3],
       [4, 2, 5, 7]])

In [26]:
print(f"first two rows, first three cols =\n{x2[:2, :3]}")

two rows, three cols =
[[3 0 8]
 [1 4 0]]


In [27]:
print(f"all rows, every other cols=\n{x2[:, ::2]}")

all rows, every other cols=
[[3 8]
 [1 0]
 [4 5]]


In [29]:
print(f"first row = \n{x2[0,:]}")

first row - 
[3 0 8 8]


## Reshape

In [33]:
# put the number 1 to 9 to 3x3 array
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# this is 1-d array
x=np.array([1,2,3])
print(f"ndim = {x.ndim}, shape = {x.shape}")

ndim = 1, shape = (3,)


In [43]:
# reshape to 2-d array, row vector
y = x.reshape((1,3))
print(f"ndim = {y.ndim}, shape = {y.shape}")

ndim = 2, shape = (1, 3)


In [46]:
# reshape it to column vector
y = x.reshape((3,1))
print(f"ndim = {y.ndim}, shape = {y.shape}")

ndim = 2, shape = (3, 1)


### using newaxis



In [45]:
# using newaxis
y = x[np.newaxis, :]
print(f"ndim = {y.ndim}, shape = {y.shape}")

ndim = 2, shape = (1, 3)


In [48]:
# using newaxis
y = x[:, np.newaxis]
print(f"ndim = {y.ndim}, shape = {y.shape}")

ndim = 2, shape = (3, 1)


## Computation on array

numpy provides many *vectorized operation* on its array, which is very efficient. It is implemented as *ufuncs*.

### Arithematics, trignometric, exponents, logarithm

A list of common operations 
```
 np.add, np.subtract, np.negative, np.multiply
 np.divide, np.floor_divide, np.power, np.mod
 np.abs, np.sin, np.cos, np.tan 
 np.log, np.log2, np.log10
 np.exp(x)      # e^x
 np.exp2(x)     # 2^x
 np.power(3,x)  # 3^x
```


## Specifying output

On large calculation, specifying output can be more efficient


In [49]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)


[ 0. 10. 20. 30. 40.]


## Aggregation